const $=s=>document.querySelector(s);
const tbody=$('#processTable tbody');
let processes=[];
let lastResults={};

function sample(){processes=[{id:'P1',at:0,bt:8,priority:2,order:0},{id:'P2',at:1,bt:4,priority:1,order:1},{id:'P3',at:2,bt:2,priority:3,order:2},{id:'P4',at:3,bt:5,priority:2,order:3},{id:'P5',at:4,bt:3,priority:1,order:4}];renderInputs();}
function addProcess(){const n=processes.length;processes.push({id:'P'+(n+1),at:n,bt:4,priority:1,order:n});renderInputs();}
function renderInputs(){tbody.innerHTML='';processes.forEach((p,i)=>{const tr=document.createElement('tr');tr.innerHTML=`<td><input class="name-input" data-i="${i}" data-k="id" value="${p.id}"></td><td><input class="process-input" type="number" min="0" data-i="${i}" data-k="at" value="${p.at}"></td><td><input class="process-input" type="number" min="1" data-i="${i}" data-k="bt" value="${p.bt}"></td><td><input class="process-input" type="number" data-i="${i}" data-k="priority" value="${p.priority}"></td><td><button class="delete-btn" data-del="${i}">Delete</button></td>`;tbody.appendChild(tr)});$('#processCount').textContent=processes.length;}
tbody.addEventListener('input',e=>{if(!e.target.dataset.i)return;const i=+e.target.dataset.i,k=e.target.dataset.k;processes[i][k]=k==='id'?e.target.value:Number(e.target.value);});
tbody.addEventListener('click',e=>{if(e.target.dataset.del!==undefined){processes.splice(+e.target.dataset.del,1);processes.forEach((p,i)=>p.order=i);renderInputs();}});
$('#addProcess').onclick=addProcess;$('#loadSample').onclick=sample;$('#clearAll').onclick=()=>{processes=[];renderInputs();$('#resultsSection').classList.add('hidden');};
$('#algorithm').onchange=()=>{$('#quantumWrap').style.display=$('#algorithm').value==='RR'?'block':'none'};

function clean(){if(processes.length<1)throw Error('Add at least one process.');const seen=new Set();return processes.map((p,i)=>{const id=String(p.id).trim()||`P${i+1}`;if(seen.has(id))throw Error('Process names must be unique.');seen.add(id);const at=Number(p.at),bt=Number(p.bt),pr=Number(p.priority);if(!Number.isFinite(at)||at<0||!Number.isInteger(at))throw Error(`${id}: Arrival Time must be a non-negative integer.`);if(!Number.isFinite(bt)||bt<=0||!Number.isInteger(bt))throw Error(`${id}: Burst Time must be a positive integer.`);if(!Number.isFinite(pr)||!Number.isInteger(pr))throw Error(`${id}: Priority must be an integer.`);return {...p,id,at,bt,priority:pr,order:i};});}
function base(ps){return Object.fromEntries(ps.map(p=>[p.id,{...p,remaining:p.bt,ct:null,first:null}]));}
function cmp(a,b,key){return a[key]-b[key]||a.at-b.at||a.order-b.order;}
function segmentsFromRuns(runs){const out=[];for(const r of runs){if(r.end<=r.start)continue;const prev=out[out.length-1];if(prev&&prev.id===r.id&&prev.end===r.start)prev.end=r.end;else out.push({...r});}return out;}
function finish(data){const metrics=Object.values(data).map(x=>{const tat=x.ct-x.at,wt=tat-x.bt,rt=x.first-x.at;return {...x,tat,wt,rt};});const avg=k=>metrics.reduce((s,x)=>s+x[k],0)/metrics.length;return {metrics,avg:{wt:avg('wt'),tat:avg('tat'),rt:avg('rt')}};}

function fcfs(ps){const d=base(ps), order=[...ps].sort((a,b)=>cmp(a,b,'at')),runs=[];let t=0;for(const p of order){if(t<p.at){runs.push({id:'IDLE',start:t,end:p.at});t=p.at}d[p.id].first=t;runs.push({id:p.id,start:t,end:t+p.bt});t+=p.bt;d[p.id].remaining=0;d[p.id].ct=t;}return {runs:segmentsFromRuns(runs),...finish(d)};}
function sjf(ps){const d=base(ps),runs=[];let t=0,done=0;while(done<ps.length){const ready=ps.filter(p=>d[p.id].ct===null&&p.at<=t);if(!ready.length){const next=Math.min(...ps.filter(p=>d[p.id].ct===null).map(p=>p.at));runs.push({id:'IDLE',start:t,end:next});t=next;continue}const p=ready.sort((a,b)=>cmp(a,b,'bt'))[0];d[p.id].first=t;runs.push({id:p.id,start:t,end:t+p.bt});t+=p.bt;d[p.id].remaining=0;d[p.id].ct=t;done++;}return {runs:segmentsFromRuns(runs),...finish(d)};}
function srtf(ps){const d=base(ps),runs=[];let t=0,done=0;while(done<ps.length){const ready=ps.filter(p=>d[p.id].ct===null&&p.at<=t);if(!ready.length){const next=Math.min(...ps.filter(p=>d[p.id].ct===null).map(p=>p.at));runs.push({id:'IDLE',start:t,end:next});t=next;continue}const p=ready.sort((a,b)=>d[a.id].remaining-d[b.id].remaining||cmp(a,b,'at'))[0];if(d[p.id].first===null)d[p.id].first=t;const nextArrival=Math.min(...ps.filter(x=>d[x.id].ct===null&&x.at>t).map(x=>x.at),Infinity);const dt=Math.min(d[p.id].remaining,nextArrival-t);runs.push({id:p.id,start:t,end:t+dt});d[p.id].remaining-=dt;t+=dt;if(d[p.id].remaining===0){d[p.id].ct=t;done++;}}return {runs:segmentsFromRuns(runs),...finish(d)};}
function priority(ps,preemptive=false){const d=base(ps),runs=[];let t=0,done=0;while(done<ps.length){const ready=ps.filter(p=>d[p.id].ct===null&&p.at<=t);if(!ready.length){const next=Math.min(...ps.filter(p=>d[p.id].ct===null).map(p=>p.at));runs.push({id:'IDLE',start:t,end:next});t=next;continue}const p=ready.sort((a,b)=>a.priority-b.priority||a.at-b.at||a.order-b.order)[0];if(d[p.id].first===null)d[p.id].first=t;if(!preemptive){runs.push({id:p.id,start:t,end:t+d[p.id].remaining});t+=d[p.id].remaining;d[p.id].remaining=0;d[p.id].ct=t;done++;}else{const nextArrival=Math.min(...ps.filter(x=>d[x.id].ct===null&&x.at>t).map(x=>x.at),Infinity);const higher=ps.filter(x=>d[x.id].ct===null&&x.at>t&&x.priority<p.priority).sort((a,b)=>a.at-b.at)[0];const stop=higher?Math.min(nextArrival,higher.at):nextArrival;const dt=Math.min(d[p.id].remaining,stop-t);runs.push({id:p.id,start:t,end:t+dt});d[p.id].remaining-=dt;t+=dt;if(d[p.id].remaining===0){d[p.id].ct=t;done++;}}}return {runs:segmentsFromRuns(runs),...finish(d)};}
function rr(ps,q){const d=base(ps),runs=[],sorted=[...ps].sort((a,b)=>cmp(a,b,'at'));let t=0,idx=0,done=0,qarr=[];while(done<ps.length){while(idx<sorted.length&&sorted[idx].at<=t)qarr.push(sorted[idx++]);if(!qarr.length){const next=sorted[idx].at;runs.push({id:'IDLE',start:t,end:next});t=next;continue}const p=qarr.shift();if(d[p.id].first===null)d[p.id].first=t;const dt=Math.min(q,d[p.id].remaining);runs.push({id:p.id,start:t,end:t+dt});d[p.id].remaining-=dt;t+=dt;while(idx<sorted.length&&sorted[idx].at<=t)qarr.push(sorted[idx++]);if(d[p.id].remaining>0)qarr.push(p);else{d[p.id].ct=t;done++;}}return {runs:segmentsFromRuns(runs),...finish(d)};}
function simulate(type,ps,q){if(type==='FCFS')return fcfs(ps);if(type==='SJF')return sjf(ps);if(type==='SRTF')return srtf(ps);if(type==='RR')return rr(ps,q);if(type==='PNP')return priority(ps,false);if(type==='PP')return priority(ps,true);}

function run(){try{const ps=clean(),type=$('#algorithm').value,q=Number($('#quantum').value);if(type==='RR'&&(!Number.isInteger(q)||q<1))throw Error('Round Robin time quantum must be a positive integer.');const r=simulate(type,ps,q);lastResults[type]=r;renderResult(type,r);$('#lastRun').textContent=type;$('html').scrollIntoView({behavior:'smooth',block:'start'});}catch(e){alert(e.message);}}
function renderResult(type,r){$('#resultsSection').classList.remove('hidden');$('#resultTitle').textContent=label(type)+' Results';$('#resultSubtitle').textContent=`${r.metrics.length} processes · ${r.runs.length} timeline segments`;$('#resultBadge').textContent='CALCULATED';const g=$('#gantt');g.innerHTML='';const total=Math.max(1,r.runs[r.runs.length-1].end);r.runs.forEach((s,i)=>{const d=document.createElement('div');d.className='gantt-segment '+(s.id==='IDLE'?'idle':'');d.style.flex=`${Math.max(.5,s.end-s.start)} 0 0`;d.innerHTML=`<div class="gantt-box">${s.id}</div><div class="gantt-time"><span>${s.start}</span>${i===r.runs.length-1?`<span>${s.end}</span>`:''}</div>`;g.appendChild(d)});const mt=$('#metricsTable tbody');mt.innerHTML='';r.metrics.sort((a,b)=>a.order-b.order).forEach(x=>{const tr=document.createElement('tr');tr.innerHTML=`<td><strong>${x.id}</strong></td><td>${x.at}</td><td>${x.bt}</td><td>${x.priority}</td><td>${x.ct}</td><td>${x.tat}</td><td>${x.wt}</td><td>${x.rt}</td>`;mt.appendChild(tr)});$('#averages').innerHTML=`<div class="avg"><span>Average Waiting Time</span><b>${r.avg.wt.toFixed(2)}</b></div><div class="avg"><span>Average Turnaround Time</span><b>${r.avg.tat.toFixed(2)}</b></div><div class="avg"><span>Average Response Time</span><b>${r.avg.rt.toFixed(2)}</b></div>`;$('#explanationText').innerHTML=explain(type,r,psFromMetrics(r.metrics));}
function psFromMetrics(m){return m.map(x=>({id:x.id,at:x.at,bt:x.bt,priority:x.priority,order:x.order}));}
function label(t){return {FCFS:'FCFS — First-Come, First-Served',SJF:'SJF — Shortest Job First',SRTF:'SRTF — Shortest Remaining Time First',RR:'RR — Round Robin',PNP:'Priority — Non-Preemptive',PP:'Priority — Preemptive'}[t]}
function explain(type,r,ps){const p=[];if(r.runs.some(x=>x.id==='IDLE'))p.push('The CPU has an idle period because no process had arrived yet.');if(type==='FCFS')p.push('FCFS is non-preemptive, so once a process starts, it runs until its burst finishes. The queue follows arrival order.');if(type==='SJF')p.push('SJF is non-preemptive and selects the shortest available burst whenever the CPU becomes free.');if(type==='SRTF')p.push('SRTF is preemptive: a newly arriving process can take the CPU when its remaining burst is shorter than the current process.');if(type==='RR')p.push(`Round Robin uses a time quantum of ${Number($('#quantum').value)}. Processes that do not finish return to the ready queue for another cycle.`);if(type==='PNP')p.push('Non-preemptive Priority selects the ready process with the smallest priority number.');if(type==='PP')p.push('Preemptive Priority can interrupt the current process when a newly available process has a smaller priority number.');p.push('Waiting time measures time spent waiting for CPU service; turnaround time measures total time from arrival to completion; response time measures how long a process waited before its first CPU execution.');p.push(`For this run, the averages are WT ${r.avg.wt.toFixed(2)}, TAT ${r.avg.tat.toFixed(2)}, and RT ${r.avg.rt.toFixed(2)}.`);return p.map(x=>`<p>• ${x}</p>`).join('');}
function compare(){try{const ps=clean(),q=Number($('#quantum').value);if(!Number.isInteger(q)||q<1)throw Error('Round Robin time quantum must be a positive integer.');const types=['FCFS','SJF','SRTF','RR','PNP'];const out=types.map(t=>({t,r:simulate(t,ps,q)}));const tb=$('#comparisonTable tbody');tb.innerHTML='';out.forEach(({t,r})=>{const tr=document.createElement('tr');tr.innerHTML=`<td><strong>${label(t)}</strong></td><td>${r.avg.wt.toFixed(2)}</td><td>${r.avg.tat.toFixed(2)}</td><td>${r.avg.rt.toFixed(2)}</td>`;tb.appendChild(tr)});const notes=$('#comparisonNotes');notes.classList.remove('hidden');notes.innerHTML=`The table compares the same ${ps.length}-process workload. Values are calculated directly from each algorithm's generated schedule. Lower or higher averages are not automatically “better” in every context; interpret them according to the performance goal being discussed. Priority uses smaller numerical values as higher priority.`;}catch(e){alert(e.message);}}
$('#runBtn').onclick=run;$('#compareBtn').onclick=compare;sample();$('#quantumWrap').style.display='none';
